### PR TITLE
Nftc

### PR DESCRIPTION
**Pull request by vuong177**

### CODE REVIEW

**Comment by faddat** [comment]
Voung, could you give us some context on this one?

We are going to need to do a ton of rework on craft beacuase of the middleware issues, please see #114

**Comment by vuong177** [comment]
> Voung, could you give us some context on this one?
> 
> We are going to need to do a ton of rework on craft beacuase of the middleware issues, please see #114

yes, i'm going to make descipt.
This PR is module-approach for craft-nft. I trying to reuse sdk-nft code and compleet it. It save so much time than use cosmwasm nft.

**Comment by faddat** [comment]
Does this code depend on the middleware stuff?

**Comment by vuong177** [comment]
> Does this code depend on the middleware stuff?

No, i see

**Comment by faddat** [comment]
Hey Vuong, I think it's likely much better to use the sdk's nft module, because of this:

https://github.com/cosmos/ibc-go/pull/1510

**Comment by vuong177** [comment]
@faddat, our NFT has some particular logic in mint, list. I have discussed this with @Reecepbcups in #101. It's why I chose to build the NFTc module instead of the SDK module.

**Comment by vuong177** [comment]
> Hey Vuong, I think it's likely much better to use the sdk's nft module, because of this:
> 
> [cosmos/ibc-go#1510](https://github.com/cosmos/ibc-go/pull/1510)
> 
> After speaking with sistla, @Reecepbcups and the stargaze team, that seems best path forward. But I may have misunderstood the intent of this PR, so if I got it wrong, please let me know OK?

I'm reading this PR to make sure our module can be enabled ICS721 or not.

**Comment by Reecepbcups** [comment]
> @faddat, our NFT has some particular logic in mint, list NFT. I have discussed this with @Reecepbcups in #101. It's why I chose to build the NFTc module instead of the SDK module.

Just FYI, I can use any NFT platform I think so long as it has attributes (JSON object encoded to string). 
I'm building off oNFT and using it atm to test against and it goes well. 

Here is an example mint I did
https://rest.flixnet-4.omniflix.network/omniflix/onft/v1beta1/onfts/onftdenom23c8ecb9a9e2484ebfc7c4847e65f15b/omniflix13na285c3llhnfenq6hl3fh255scljcue4td9nh

**Comment by vuong177** [comment]
@faddat I'm going to use SDK module and close this PR.

**Comment by faddat** [comment]
ok.  @vuong177 keep the code around in its branch please.  Thanks!

**Comment by sascha1337** [comment]
how far is the https://github.com/cosmos/ibc-go/pull/1510 ICS721 to be used in production?

**Pull request closed without merging**
